I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 24, in script
    scene memory_path with dissolve(1.0)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 24, in script
    scene memory_path with dissolve(1.0)
  File "/Users/fallingyuki/Documents/renpy-7.4.4-sdk/renpy/ast.py", line 1397, in execute
    renpy.exports.with_statement(trans, paired)
  File "/Users/fallingyuki/Documents/renpy-7.4.4-sdk/renpy/exports.py", line 1646, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Users/fallingyuki/Documents/renpy-7.4.4-sdk/renpy/display/core.py", line 2610, in do_with
    clear=clear)
  File "/Users/fallingyuki/Documents/renpy-7.4.4-sdk/renpy/display/core.py", line 3101, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/Users/fallingyuki/Documents/renpy-7.4.4-sdk/renpy/display/core.py", line 3460, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Darwin-20.4.0-x86_64-i386-64bit
Ren'Py 7.4.4.1439
art74_final 1.0
Fri May 21 08:45:41 2021
